### ISSUE TITLE
Release 0.0.17

### ISSUE THREAD

**Issue by rusheb** [mivanit/muutils#3]
## Issue
test_generation.py from `maze_transformer` cannot run due to a dependency on `muutils.misc.list_split`, which is not available in v0.0.16

Stack trace:

```
Traceback (most recent call last):
  File "/Users/rusheb/code/maze-transformer/scripts/test_generation.py", line 5, in <module>
    from maze_transformer.evaluation.plot_maze import plot_path
  File "/Users/rusheb/code/maze-transformer/src/maze_transformer/evaluation/plot_maze.py", line 8, in <module>
    from maze_transformer.generation.latticemaze import LatticeMaze
  File "/Users/rusheb/code/maze-transformer/src/maze_transformer/generation/latticemaze.py", line 14, in <module>
    from muutils.misc import list_split
ImportError: cannot import name 'list_split' from 'muutils.misc' (/Users/rusheb/code/maze-transformer/venv/lib/python3.10/site-packages/muutils/misc.py)
```

## Workaround
Clone this project and installing as an editable package (`pip install -e /path/to/muutils`) from the consumer.

This works because the function was added in e45ade948f5588aa674dec1a495137c06f5b7be7, after the release of 0.0.16.

## Solution
We should release v0.0.17 to make this function available in pypi.

**Comment by rusheb** [comment]
Resolved by https://github.com/mivanit/muutils/releases/tag/v0.2.0
